### ISSUE TITLE
Unable to enter commands from the console interface

### ISSUE THREAD

**Issue by zhandonbi** [SmartlyDressedGames/U3-Docs#18] opened 2020-02-01 11:24 UTC
My server is running on Centos, and after I start the server, I can't type any instructions, that is, I can't type any characters

**Comment by DoggySazHi** [comment] 2020-04-12 00:58
So, since it seems that there are no developments towards making Linux more-or-less usable (RCON? Actually joining the server to issue admin commands?), I'll try to shed some light on what's happening.

So, almost a year ago, I had complaints about the new Unturned Dedicated Server not having by default, console support on *nix-based operating systems. It wouldn't register any form of user IO, even blocking signal controls from running (Ctrl+C didn't work, had to open another terminal to kill the process.) Here's an image of such not working.

![failterminate](https://user-images.githubusercontent.com/42221528/79057931-c1773e00-7c1b-11ea-8905-72b40c48cc77.png)
(This actually uses ServerHelper.sh, however my point was that before, it didn't work either back then).

However, I figured out that RocketLauncher.exe still functions as a way to retrieve this console functionality back, which was documented in an old revision on the [official Unturned Wiki.](https://wiki.smartlydressedgames.com/w/index.php?title=Linux_dedicated_server&oldid=11417) This approach is now deprecated (hence the new revisions) and plus, doesn't work, using the wrong output. Even getting this to "work" now in the first place is unusual, as it requires symlinking the Unturned_Headless.x86_64 to Unturned_Headless.x86, and then using the Mono runtime to launch RocketLauncher.exe. Now with the new updates, it pipes the wrong output, however you can kill the server using Ctrl + C rather than opening a new terminal and killing the process.

So now we have two ways to start the server, the ServerHelper.sh (which can't be killed with a user SIGINT) and RocketLauncher.exe, which is completely deprecated and doesn't give the right log output. So, what might be the problem?

Back to a year ago, I asked Molt specifically if he can ask about the console not working. This was the response from Nelson.
![serverconsole](https://user-images.githubusercontent.com/42221528/79058027-34cd7f80-7c1d-11ea-8ed0-df13dbf219af.png)

And to confirm, the Linux Dedicated Servers are **STILL** trying to load Kernel32 (at least by the time this is posted).
![image](https://user-images.githubusercontent.com/42221528/79058053-9aba0700-7c1d-11ea-97e2-d8e63791a93b.png)

I don't know much about Unity programming, but I know this for sure: the Mono runtime has Console.ReadLine()/ReadKey(), which is probably much better than directly binding to Kernel32, and plus, it's assured to run on *nix-based OSes and Windows. I can't provide a solution, but I hope this helps to resolving what might be the problem.

(This was reproduced on both Ubuntu 19.04 and on Fedora 31, with the same problems on both)

**Comment by SDGNelson** [comment] 2020-04-14 02:01
Following up on this:

Unfortunately many many many server hosts are still using old builds of RocketMod which interfere with the game's terminal IO on Linux. If you use the "officialish" build of RocketMod from the Extras directory then you can enable the newer built-in terminal IO handling with the `-ThreadedConsole` command-line flag.

Using the newer handler will do a clean shutdown on Linux when Ctrl-C or Ctrl-Break are intercepted. (Notify all players, save, and close.)

Soon™ my plan is to detect older versions of RocketMod in order to warn hosts that they need to upgrade. Then the `-ThreadedConsole` can be made default on Linux.

Regarding Windows code: Unturned only dynamically links kernel32 on Windows for alloc/free console and setting the codepage. These are stripped out on non-Windows platforms, so the output you see might be from a plugin or old RocketMod.

**Comment by SDGNelson** [comment] 2020-04-29 23:10
In the next update the game will warn about out-of-date versions of RocketMod. In the update after that it will become mandatory, and this can become the default.

**Comment by SDGNelson** [comment] 2020-07-11 00:31
-ThreadedConsole is finally the default following today's 3.20.6.0 update!

**Closed by SDGNelson** 2020-07-11 00:31 UTC
